"""
Draft privacy policy generator using Claude API.
Takes scan results (gap analysis per APP) and generates a tailored privacy policy.
"""
import json
import os
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY')
MODEL = 'claude-sonnet-4-6'

DISCLAIMER_HEADER = (
    "DRAFT PRIVACY POLICY\n"
    "Generated by PrivacySorted. This is an AI-generated draft based on an automated "
    "scan of your website. It is not legal advice. We recommend having this draft "
    "reviewed by a qualified privacy lawyer before publishing."
)

DISCLAIMER_FOOTER = (
    "This document was generated on {date} by PrivacySorted (privacysorted.com). "
    "PrivacySorted is not a law firm and does not provide legal advice. This draft "
    "is provided as a starting point for your privacy compliance journey."
)

SYSTEM_PROMPT = """You are an Australian privacy law specialist. Your task is to draft a privacy policy for an Australian business that complies with the Privacy Act 1988 and the 13 Australian Privacy Principles (APPs).

Rules:
- Write in plain English suitable for a small business website
- Address EVERY gap identified in the scan results
- Use the business name and sector to tailor language appropriately
- Include all 13 APPs, even those marked compliant (reinforce good practices)
- Structure with clear headings for each APP area
- Include practical specifics (not just generic template language)
- Do NOT include any legal disclaimers (those are added separately)
- Output the policy text only, no preamble or explanation

Structure the policy with these sections:
1. About this policy (APP 1)
2. Anonymity and pseudonymity (APP 2)
3. Collection of personal information (APP 3)
4. Dealing with unsolicited information (APP 4)
5. Notification of collection (APP 5)
6. Use and disclosure (APP 6)
7. Direct marketing (APP 7)
8. Cross-border disclosure (APP 8)
9. Government identifiers (APP 9)
10. Quality of personal information (APP 10)
11. Security of personal information (APP 11)
12. Access to personal information (APP 12)
13. Correction of personal information (APP 13)
14. How to make a complaint
15. How to contact us"""


def _build_prompt(scan_result):
    """Build the user prompt from scan results."""
    business_name = scan_result.get('business_name', 'the business')
    sector = scan_result.get('sector', 'General')
    url = scan_result.get('url', '')
    analysis = scan_result.get('analysis', {})
    apps = analysis.get('apps', [])
    policy_excerpt = scan_result.get('policy_excerpt', '')

    lines = [
        f"Business: {business_name}",
        f"Website: {url}",
        f"Sector: {sector}",
        f"Overall compliance score: {analysis.get('overall_score', 0)}/100",
        "",
        "## Scan Results by Australian Privacy Principle",
        "",
    ]

    for app in apps:
        app_num = app.get('app_number', '?')
        app_name = app.get('app_name', '')
        status = app.get('status', 'UNKNOWN')
        gaps = app.get('gaps', [])
        recs = app.get('recommendations', [])

        lines.append(f"### APP {app_num}: {app_name}")
        lines.append(f"Status: {status}")
        if gaps:
            lines.append("Gaps found:")
            for g in gaps:
                lines.append(f"  - {g}")
        if recs:
            lines.append("Recommendations:")
            for r in recs:
                lines.append(f"  - {r}")
        lines.append("")

    if policy_excerpt:
        lines.append("## Existing policy excerpt (first 500 chars)")
        lines.append(policy_excerpt)
        lines.append("")

    lines.append(
        "Draft a complete privacy policy for this business that addresses "
        "all identified gaps while maintaining any existing compliant practices."
    )

    return '\n'.join(lines)


def generate_draft(scan_result):
    """Generate a draft privacy policy from scan results.

    Returns dict with 'draft_text', 'generated_at', 'model'.
    Raises on failure.
    """
    if not ANTHROPIC_API_KEY:
        raise RuntimeError("ANTHROPIC_API_KEY not set")

    import requests

    user_prompt = _build_prompt(scan_result)

    resp = requests.post(
        'https://api.anthropic.com/v1/messages',
        headers={
            'x-api-key': ANTHROPIC_API_KEY,
            'anthropic-version': '2023-06-01',
            'content-type': 'application/json',
        },
        json={
            'model': MODEL,
            'max_tokens': 4096,
            'system': SYSTEM_PROMPT,
            'messages': [{'role': 'user', 'content': user_prompt}],
        },
        timeout=120,
    )
    resp.raise_for_status()
    data = resp.json()

    draft_text = ''
    for block in data.get('content', []):
        if block.get('type') == 'text':
            draft_text += block['text']

    if not draft_text.strip():
        raise RuntimeError("Empty draft returned from API")

    generated_at = datetime.utcnow().strftime('%d %B %Y')

    # Add disclaimers
    full_draft = (
        DISCLAIMER_HEADER + "\n\n"
        + "---\n\n"
        + draft_text.strip() + "\n\n"
        + "---\n\n"
        + DISCLAIMER_FOOTER.format(date=generated_at)
    )

    return {
        'draft_text': full_draft,
        'draft_raw': draft_text.strip(),
        'generated_at': datetime.utcnow().isoformat(),
        'model': MODEL,
    }
